config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  resources :categories, only: [:index, :show, :new, :create, :destroy] do
    resources :records, only: [ :new, :show, :create, :destroy]
  end


  authenticated :user do
    root :to => 'categories#index', as: :authenticated_root
  end

  root to: 'splash#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true

  belongs_to :user
  has_one_attached :icon
  has_many :category_records, dependent: :destroy
  has_many :records, through: :category_records, dependent: :destroy
end

app/models/category_record.rb
class CategoryRecord < ApplicationRecord
  belongs_to :category
  belongs_to :record
end

app/models/record.rb
class Record < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true

  belongs_to :user
  has_many :category_records, dependent: :destroy
  has_many :categories, through: :category_records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 1, maximum: 50 }
  has_many :categories, dependent: :destroy
  has_many :records, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.where(user_id: current_user.id)
  end

  def show
    @category = Category.find(params[:id])
    @records = @category.records.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.create(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:user_id, :name, :icon)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[show edit update destroy]

  # GET /records/1 or /records/1.json
  def show; end

  # GET /records/new
  def new
    @category = Category.find(params[:category_id])
    @record = Record.new
  end

  def create
    @category = Category.find(params[:category_id])
    @record = @category.records.create(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to category_path(@category), notice: 'Transaction was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy
    @category = Category.find(params[:category_id])

    respond_to do |format|
      format.html { redirect_to category_path(@category), notice: 'Transaction was removed successfully.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_record
    @record = Record.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def record_params
    params.require(:record).permit(:user_id, :name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <div class="my-6 border-solid border-1 bg-[#F5F5F5] p-4 mx-4 cursor-pointer">
    <div class="flex justify-between md:w-1/2">
      <% if category.icon.attached? %>
        <%= image_tag category.icon, class: "w-32 h-32 object-cover rounded-lg" %>
      <% else %>
        <img
          src="https://cdn.tailgrids.com/1.0/assets/images/cards/card-01/image-01.jpg"
          alt="image"
          class="w-32 h-32"
        />
      <% end %>
      <div class="flex flex-col justify-center">
        <h5 class="font-bold italic text-2xl"><%= category.name %><h5>
        <h5 class="font-bold text-sm">Total: $<%= category.records.sum(:amount) %></h5>
      </div>
    </div>
  </div> 
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :category_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="mx-6">
    <% form.label :name, required: true, style: "display: block" %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>
  <br />
  <br />
  <div class="mx-6">
    <% form.label :icon, required: true, style: "display: block" %>
    <%= form.file_field :icon, direct_upload: true, class:"form-control", placeholder:"Icon" %>
  </div>
  <br />
  <div class="mx-6">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<nav class="bg-[#3778C2] text-white p-2">
  <ul class="flex justify-between mr-6">
    <li class="text-4xl">
      <i class="fa fa-navicon"></i>
    </li>
    <li>
      <h2 class="font-bold text-3xl">Categories</h2>
    </li>
    <li class="font-bold text-4xl">
      <%= button_to destroy_user_session_path, method: :delete do %>   
        <i class="fa fa-sign-out"></i>
      <% end %>
    </li>
  </ul>
</nav>
<%= render 'layouts/alerts' %>
<div id="categories">
  <% if @categories.any? %>
    <% @categories.each do |category| %>
      <%= link_to category_path(category), class: "text-black no-underline" do %>
        <%= render category %>
      <% end %>
    <% end %>
  <% else %>
  <p class="text-base text-center font-bold">There are no categories. Please add a category</p>
  <% end %>
</div>
<div class="bg-[#5FB523] p-2 flex justify-center fixed-bottom">
  <%= link_to "New category", new_category_path, class: "btn btn-outline-light w-75 p-2" %>
<div>

app/views/categories/new.html.erb
<nav class="bg-[#3778C2] text-white p-1">
  <ul class="flex justify-start gap-5 p-2">
    <li class="text-3xl mr-4">
      <%= link_to categories_path, class: "text-white" do %>
        <i class="fa fa-arrow-left"></i>
      <% end %>
    </li>
    <li>
      <h2 class="font-bold text-3xl">Add Category</h2>
    </li>
  </ul>
</nav>

<div class="my-20">
  <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<nav class="bg-[#3778C2] text-white p-1">
  <ul class="flex justify-between items-center mr-6 mt-2">
    <li class="text-3xl">
      <%= link_to categories_path, class: "text-white" do %>
        <i class="fa fa-arrow-left"></i>
      <% end %>
    </li>
    <li>
      <h2 class="font-bold text-xl pt-3">Category Details</h2>
    </li>
    <li class="font-bold text-4xl">
      <%= button_to destroy_user_session_path, method: :delete do %>   
        <i class="fa fa-sign-out"></i>
      <% end %>
    </li>
  </ul>
</nav>
<%= render 'layouts/alerts' %>
<%= render @category %>
<div class="mx-6">
  <%= button_to "Delete Category", @category, method: :delete, class: "btn btn-danger"%>
</div>


<h1 class="text-center font-bold text-xl mt-12">Transactions</h1>
<div class="d-flex justify-content-end mr-6 my-3">
  <%= link_to "New Transaction", new_category_record_path(@category), class: "btn btn-primary" %>
</div>

<% if @category.records.any? %>
  <div class="mx-4 md:mx-48 border-solid border-1 bg-[#F5F5F5] p-4">
    <% @category.records.order(created_at:'DESC').each do |record| %>
      <div class="flex justify-between border-solid border-1 bg-white py-3 px-4 mb-3">
        <div class="flex flex-col justify-center pt-1">
          <p class="font-bold italic"><%= record.name %></p>
          <p class="font-bold italic"><%= record.created_at.strftime("%d-%b-%Y")%></p></p>
        </div>
        <div class="flex flex-col">
          <p class="font-bold">$<%= record.amount %></p>
          <%=button_to "Delete", category_record_path(category_id: @category.id, id: record.id), method: :delete, class:"btn btn-primary px-2"%>
        </div>
      </div>
    <% end %>
  <div>
<% else %>
  <p class="font bold italic text-center text-base mx-6">There are no transactions to show. Please Add new Transaction</p>
<% end %>

app/views/layouts/_alerts.html.erb
<%if notice%>
<div class="alert alert-success alert-dismissible fade show" role="alert">
<strong><%= notice %></strong>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end%>
<%if alert%>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<strong> <%= alert %> </strong>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with(model: [@category, @category.records.create]) do |form| %>
  <% if record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :record_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="mx-6">
    <% form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>
  <br />
  <div class="mx-6">
    <% form.label :amount, style: "display: block" %>
    <%= form.text_field :amount, class:"form-control", placeholder:"Amount" %>
  </div>
  <br />
  <div class="mx-6">
    <% form.label :category, style: "display: block" %>
    <%= form.text_field :category, value:@category.name, class:"form-control" %>
  </div>
  <br />
  <div class="mx-6">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/records/new.html.erb
<nav class="bg-[#3778C2] text-white py-2">
  <ul class="flex justify-between mr-4">
    <li class="text-3xl">
      <%= link_to category_path(@category), class: "text-white" do %>
        <i class="fa fa-arrow-left"></i>
      <% end %>
    </li>
    <li>
      <h2 class="font-bold text-2xl">New Transaction</h2>
    </li>
    <li class="font-bold text-4xl">
      <%= button_to destroy_user_session_path, method: :delete do %>   
        <i class="fa fa-sign-out"></i>
      <% end %>
    </li>
  </ul>
</nav>

<div class="py-20">
  <%= render "form", record: @record %>
</div>

<br>

app/views/splash/index.html.erb
<div class="flex flex-col gap-4 justify-center items-center my-36 font-bold">
  <div class="mx-6 flex flex-col gap-2">
    <%= image_tag "budget.png" %>
    <h5 class="text-[#9D47FF] text-center italic">TranXtrack</h5>
  </div>

  <div class="border-solid border-1 bg-[#3778C2] w-11/12 text-center p-2">
    <%= link_to "Log in", new_user_session_path, class: "text-decoration-none text-white" %>
  </div>
  <div class="border-solid border-1 bg-[#3778C2] w-11/12 text-center p-2">
    <%= link_to "Sign Up", new_user_registration_path, class: "text-decoration-none text-white"%>
  </div>
</div>